set number
set title
set tabstop=4
set expandtab
set shiftwidth=4
set smartindent
set virtualedit=block
set backspace=indent,eol,start
syntax on
set encoding=utf-8
set fileencodings=utf-8,iso-2022-jp,euc-jp,sjis
set fileformats=unix,dos,mac
